# Generated by Django 4.2 on 2025-06-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0002_unidades_alter_categoria_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
