# Generated by Django 4.2 on 2025-06-18 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0003_unidades_estado_alter_cliente_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='categorias',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='unidades',
            new_name='unidad',
        ),
    ]
