# Generated by Django 4.2 on 2025-06-28 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0005_cabeceraventas_tipo_cliente_ruc_dni_parametros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametros',
            name='id',
        ),
        migrations.AlterField(
            model_name='parametros',
            name='tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ventasapp.tipo'),
        ),
    ]
