# Generated by Django 4.2 on 2025-06-28 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0006_remove_parametros_id_alter_parametros_tipo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='tipo_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ventasapp.tipo'),
        ),
    ]
