# Generated by Django 4.2 on 2025-06-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0007_alter_parametros_tipo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventas',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cabeceraventas',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasapp.cliente'),
        ),
        migrations.AlterField(
            model_name='cabeceraventas',
            name='tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasapp.tipo'),
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='venta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventasapp.cabeceraventas'),
        ),
    ]
